FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04

# Pick up some TF dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        vim \
        wget \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python \
        python-numpy \
      	python-dev \
        python-tk \
        rsync \
        software-properties-common \
        unzip \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip --no-cache-dir install \
        ipykernel \
        jupyter \
        matplotlib \
        scipy \
        sklearn \
        pandas \
        Pillow \
        plinkio \
	six \
        && \
    python -m ipykernel.kernelspec


ENV PLINK_VERSION 1.90
ENV PLINK_ZIP plink_linux_x86_64.zip
ENV PLINK_DIR /opt/plink2

RUN set -ex \
    && apt-get update && apt-get install -y unzip curl \
    && curl -fSL "http://s3.amazonaws.com/plink2-assets/plink2_linux_i686_20170702.zip" -o $PLINK_ZIP \
    && mkdir $PLINK_DIR \
    && unzip $PLINK_ZIP -d $PLINK_DIR \
    && rm $PLINK_ZIP


# Install TensorFlow GPU version.
RUN pip --no-cache-dir install \
    https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.2.1-cp27-none-linux_x86_64.whl

# For CUDA profiling, TensorFlow requires CUPTI.
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

# symlink for plink2
RUN cd /usr/local/bin \
    && ln -s $PLINK_DIR/plink plink2


# TensorBoard
EXPOSE 6006
# IPython
EXPOSE 8888

COPY . /usr/local/diet_code/

# set workdir and make dietnet
WORKDIR "/usr/local/diet_code/dietnetwork"


# copy dir
COPY launch.sh /usr/local/diet_code 
RUN chmod +x /usr/local/diet_code/launch.sh


#ENTRYPOINT ["./launch.sh"]
RUN ["/bin/bash"]
